#!/usr/bin/env python
# -*- coding: utf-8 -*-

__doc__ = \
"""
Run dedupe on all ingested media, to generate two lookup tables:

   {global_image_id:cluster_id}
   {cluster_id:global_image_id}


## Process

Baseline approach uses manual engineered features having minimal flexibility and minimal training supervision used only
for e.g. adjusting the similarity threshold hyperparameter.

Advanced approach relies on more flexible models, trained via supervised training data, and with less reliance on
manual feature engineering or hyper-parameter tuning.

1) [Baseline & Advanced]: For all ingested media, lookup ~100 candidate duplicates. This can be done by:
   - Exact matching on feature-engineered blocking predicates
     (e.g. exact match on stemmed and normalized text strings.)
   - Approximate kNN on unsupervised, feature-engineered hashing descriptors or vector embeddings
     (e.g. pHash, dHash, tf-IDF).
   - Approximate kNN lookup, on vectors created from a model learned via training supervision
     (e.g. Representation learning model trained on a margin ranking triplet-loss.)
2) [Baseline]: It decides there's a match if a pair of media exceeds a similarity threashold.
3) [Advanced]: applies a second layer of dedupe classification on all pairs in each candidate block.
4) [Baseline & Advanced]: Pairwise decisions are fed into an agglomerative clustering, producing a flat clustering.


TODO:
   - Migrate from simple baselines to sophisticated models.
   - Store dedupe lookup tables on something other than ES?

"""

import tornado
import tornado.gen
import json

from mc_generic import setup_main, pretty_print
from mc_ingestion import es_connect, decode_image
from elasticsearch.helpers import parallel_bulk, scan

from PIL import Image
from cStringIO import StringIO

import imagehash
import binascii
import numpy as np

import mc_config

@tornado.gen.coroutine
def dedupe_lookup_async(media_id,
                        duplicate_mode = 'baseline',
                        incremental = False,
                        es = False,
                        ):
    """
    Get list of all duplicates of a media work, from previously-generated duplicate lookup tables
    generated by `dedupe_all`.
    
    `baseline` mode: Starting with simple exact-matching on an engineered content-based semantic hash.
    
    `advanced` mode: TODO.

    (TODO: may just convert this function to a non-async version with timeouts.)    
    
    Args:
        q_media:         Media to look up. See `Media Identifiers`.
        duplicate_mode:  Semantic duplicate type or matching mode. For now, defaults to 'baseline'.
        incremental:     Attempt to dedupe never-before-seen media file versus pre-ingested media files.
        es:              Database client handle. For `baseline`, it's an elasticsearch client handle.

    Returns:
                         List of matching media IDs of form: [{'id':'ifps://123...'}, {'id':'ifps://456...'},...]
    """
    
    assert duplicate_mode == 'baseline','SELECTED_DUPLICATE_MODE_NOT_IMPLEMENTED'

    #raise tornado.gen.Return([])

    if True:
        
        ### Trivial baseline can take a shortcut that uses fewer indexes / fewer writes:
        
        rr = yield es.search(index = 'getty_test',
                             type = 'image',
                             source = {'query':{"constant_score":{"filter":{"term":{ "_id" : media_id}}}},
                                       'size':1,
                                       },
                             )

        rr = json.loads(rr.body)
        
        if not rr['hits']['hits']:
            raise tornado.gen.Return([])
        
        hit = rr['hits']['hits'][0]
        hh = hit['_source']['doc']

        print ('GOT_HASH',hh['dedupe_hsh'])
        
        rr = yield es.search(index = 'getty_test',
                             #type = 'image',
                             source = {"query" : {"constant_score":
                                                  {"filter":{"term":{ "dedupe_hsh" : hh['dedupe_hsh']}}}}},
                             )

        rr = json.loads(rr.body)
        
        if not rr['hits']['hits']:            
            raise tornado.gen.Return([])
        
        rr = [hit['_source']['doc']['_id']
              for hit
              in rr['hits']['hits']
              #if hit['_source']['doc']['_id'] != media_id
              ]
        
        raise tornado.gen.Return(rr)
    
    else:

        ### We'll use this method instead, once we move beyond the trivial baseline:
        
        #Lookup cluster ID for media ID:    
        
        rr = yield es.search(index = mc_config.INDEX_NAME_MID_TO_CID,
                             type = mc_config.DOC_TYPE_MID_TO_CID,
                             source = {"query" : {"constant_score":{"filter":{"term":{ "_id" : media_id}}}},
                                       'size':1,
                                       },
                             )
        
        if not rr['hits']['hits']:

            raise tornado.gen.Return([])
        
        else:
            #Lookup all media IDs in that cluster:
            
            hit = rr['hits']['hits'][0]
            hh = hit['_source']['doc']
            
            rr = yield es.multi_search(index = mc_config.INDEX_NAME_CID_TO_CLUSTER,
                                       type = mc_config.DOC_TYPE_CID_TO_CLUSTER,
                                       source = {"query" : {"constant_score":{"filter":{"term":{ "_id" : hh['c_id']}}}}},
                                       )

            if not rr['hits']['hits']:
                raise tornado.gen.Return([])

            hit = rr['hits']['hits'][0]
            hh = hit['_source']['doc']

            raise tornado.gen.Return(hh['cluster'])



def dedupe_background(duplicate_mode = 'baseline',
                      incremental = False,
                      batch_size = 100,
                      ):
    """
    Regenerate duplicate lookup tables.
    
    Currently implements a dumb, simple, greedy, in-memory baseline.
    
    Performance Note:
    Usually it's considerably more efficient to do this in large batches rather than to attempt to dedupe online, for
    each new media file.
    
    Args: 
        duplicate_mode:  Semantic duplicate type. For now, defaults to 'baseline'.
        incremental:     If True, only update clusters affected by newly ingested media. Otherwise, regenerate
                         all dedupe clusters. Note: the more records that are deduped simultaneously, the greater
                         the efficiency.
    
    Returns:
        Check program exit status.
    """
    
    assert duplicate_mode == 'baseline','DUPLICATE_MODE_NOT_IMPLEMENTED'

    def do_commit(rrr):
        print ('COMMITTING BATCH...',len(rrr))
        for is_success,res in parallel_bulk(es,
                                            rrr,
                                            thread_count = 1,
                                            chunk_size = 500,
                                            max_chunk_bytes = 100 * 1024 * 1024, #100MB
                                            ):
            #print is_success,res
            pass
        
        rrr[:] = []
        print ('COMMITTED')
    
    es = es_connect()    
    
    res = scan(client = es,
               index = mc_config.INDEX_NAME,
               doc_type = mc_config.DOC_TYPE,
               scroll = '5m', #TODO - hard coded.
               query = {"query": {'match_all': {}
                                 },
                       #'from':0,
                       #'size':1,                           
                       },
               )
    
    print ('(1) Generate baseline image descriptors...')
    
    hash_to_ids = {}
    
    rr = []

    for c,hit in enumerate(res):
        
        hh = hit['_source']['doc']
                
        img = Image.open(StringIO(decode_image(hh['image_thumb'].encode('utf8'))))
        
        hsh = binascii.b2a_hex(np.packbits(imagehash.dhash(img, hash_size = 16).hash).tobytes())
        
        if False:
            
            ### Can skip this for the trivial baseline:
            
            if hsh not in hash_to_ids:
                hash_to_ids[hsh] = []
            hash_to_ids[hsh].append(hh['_id'])
        
        rr.append({'_op_type': 'update',
                   '_index': mc_config.INDEX_NAME,
                   '_type': mc_config.DOC_TYPE,
                   '_id': hh['_id'],
                   'body': {'doc':{'dedupe_hsh': hsh}},
                   #'body':{
                   #    "script" : "ctx._source.dedupe_hsh = hsh",
                   #    "params" : {
                   #        "dedupe_hsh" : hsh,
                   #    }
                   #   }
                   })                       
        
        print ('ADD',c,rr)
        
        if len(rr) >= batch_size:
            do_commit(rr)
        
    if rr:
        do_commit(rr)

    print ('REFRESHING', mc_config.INDEX_NAME)
    es.indices.refresh(index = mc_config.INDEX_NAME)
    print ('REFRESHED')

    if False:
        
        ### Can skip these for the trivial baseline:

        rr = []

        for c_id, (hsh, cluster) in enumerate(hash_to_ids.iteritems()):

            #Media ID -> Cluster ID:
            for mid in cluster:
                rr.append({'_op_type': 'insert',
                           '_index': mc_config.INDEX_NAME_MID_TO_CID,
                           '_type': mc_config.DOC_TYPE_MID_TO_CID,
                           '_id': mid,
                           'doc': {'c_id': cn},
                           })

            #Cluster ID -> Cluster:
            rr.append({'_op_type': 'insert',
                       '_index': mc_config.INDEX_NAME_CID_TO_CLUSTER,
                       '_type': mc_config.DOC_TYPE_CID_TO_CLUSTER,
                       '_id': c_id,
                       'doc': {'cluster': cluster},
                       })

            if len(rr) >= batch_size:
                do_commit(rr)
        if rr:
            do_commit(rr)

    
    print ('DONE_DEDUPE')
    
    


functions=['dedupe_background',
           ]

def main():    
    setup_main(functions,
               globals(),
               )

if __name__ == '__main__':
    main()

